version: '3'

services:
  api:
    build: .
    container_name: contreaul-api
    networks:
      - contreaul-net
    env_file:
      - .env
    ports:
      - "8080:8080"

networks:
  contreaul-net:
    external: true